### ISSUE TITLE
Code Update

### ISSUE THREAD

**Issue by maxwkut** [maxwkut/Web-Traffic-Forecasting#4]
I just updated the V3 file to reflect the document structure we talked about and started writing a little for the results section. Sam, I think it's best if you finish the coding part and let us know if you need help. Otherwise we just get in each other's way. When you are done with one of the sections you can update the file and we can help with writing.

Side note: I think we should not include much output from the auto arima model given that he encouraged us not to use it.

**Comment by samuelburge** [comment]
I'm working on the code right now; I actually just tried running ARMA(1,2), ARMA(2,1), and ARMA(1,1) models and I am actually getting better model selection criterion and accuracy on the test set. I think we should opt for a simpler model. I'm going to upload the updated code file with Max's changes in just a little while for you all to take a look.
